# Generated by Django 4.0.2 on 2022-08-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirantes',
            fields=[
                ('ficha', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ingles', models.CharField(max_length=50)),
                ('promedio', models.PositiveSmallIntegerField()),
                ('carrera', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
    ]
